spring.application.name=Por-do-Sol
spring.jpa.hibernate.ddl-auto=update
												 #nome database  
spring.datasource.url=jdbc:mysql://localhost:3306/projeto-por-do-sol
server.servlet.context-path=/projeto-por-do-sol
spring.datasource.username=root123
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

api.security.token.secret=${JWT_SECRET:shaveCecreta}